theme: cayman
title: Sarah Jing's Homepage
description: My personal site about AI, coding, and travels
author: Sarah Jing
email: your_email@example.com
social_links:
  - github: sarahjing228
  - linkedin: sarahjing